enum TRANSACTION_STATUS {
	PROCESSING = "PROCESSING",
	CONFIRMED = "CONFIRMED",
	FAILED = "FAILED",
}

enum MILEAGE_STATUS {
	REVIEWING = "REVIEWING", // 심사 중 상태
	REJECTED = "REJECTED", // 거절 상태
	APPROVED = "APPROVED", // 승인 상태
}

enum POINT_TYPE {
	FIXED = "FIXED", // 기본 배점
	OPTIONAL = "OPTIONAL", // 선택 배점
}

enum MILEAGE_POINT_HISTORY_TYPE {
	MILEAGE_APPROVED = "MILEAGE_APPROVED",
	MILEAGE_MINTED = "MILEAGE_MINTED",
	MILEAGE_BURNED = "MILEAGE_BURNED",
}

export { TRANSACTION_STATUS, MILEAGE_STATUS, POINT_TYPE, MILEAGE_POINT_HISTORY_TYPE };
